name: Publish Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install PIP
      run: sudo apt update && apt install python3-pip

    - name: Install Conan
      run: pip install conan && source ~/.profile

    - name: Add conan remote
      run: conan remote add LightbowConan ${{secrets.CONAN_REGISTRY_URL}}

    - name: Add conan user
      run: conan user ${{secrets.CONAN_REGISTRY_USER}} -p ${{secrets.CONAN_REGISTRY_PASSWORD}} -r LightbowConan

    - name: Run Conan Create
      run: conan create ${{github.workspace}} --build=missing

    - name: Run Conan Upload
      run: conan upload gamepackages -r=LightbowConan
